---
extends: stylelint-config-standard
rules:
  # https://www.w3.org/TR/CSS21/fonts.html#propdef-font-family
  # https://drafts.csswg.org/css-fonts-3/#propdef-font-family
  font-family-name-quotes: always-where-recommended
  function-url-quotes: # https://www.w3.org/TR/css3-values/#urls
    - always
    - except: [empty]
  selector-attribute-quotes: always # https://mathiasbynens.be/notes/unquoted-attribute-values
  string-quotes: single

  # Autoprefixer handles prefixes
  at-rule-no-vendor-prefix: true
  media-feature-name-no-vendor-prefix: true
  property-no-vendor-prefix: true
  selector-no-vendor-prefix: true
  value-no-vendor-prefix: true

  font-weight-notation: named-where-possible
  function-url-no-scheme-relative: true # https://twitter.com/paul_irish/status/588502455530311680
  max-line-length: 140
